### ISSUE TITLE
self-update？

### ISSUE THREAD

**Issue by nobuhiko** [EC-CUBE/ec-cube.github.io#13]
### venderの更新について

* composer.jsonに変更がない場合vendor/の上書きは不要です
* composerが利用可能な環境の場合vendorの上書きではなく以下でも可能です

```
> php composer.phar self-update
```

self-updateってcomposer自体を最新にアップデートするコマンドのような気が？

**Comment by chihiro-adachi** [comment]
@nobuhiko ありがとうございます。#15 で修正しています。
