### ISSUE TITLE
URL 404 :Not found http://doc.ec-cube.net/plugin-table

### ISSUE THREAD

**Issue by jaassoon** [EC-CUBE/ec-cube.github.io#167]
in URL http://doc.ec-cube.net/customize_policy
データベースの拡張について
新たな項目が必要な場合、[テーブルの追加](http://doc.ec-cube.net/plugin-table)を参考に

**Comment by jaassoon** [comment]
and
http://doc.ec-cube.net/plugin-pageadd
http://doc.ec-cube.net/plugin-pagedelete
maybe more

**Comment by chihiro-adachi** [comment]
fixed #168 

@jaassoon thank you.
