### ISSUE TITLE
FormTypeのカスタマイズページ ファイル名修正漏れ

### ISSUE THREAD

**Issue by apple-x-co** [EC-CUBE/ec-cube.github.io#208]
対象ページ
FormTypeのカスタマイズ
http://doc4.ec-cube.net/customize_formtype

誤
> サンプル
> 会員登録ページのフォームを拡張して、会社名を入力必須項目に変更するサンプルです。
> ./app/Customize/Form/Extension/EntryTypeBirthdayExtension.php

正
> サンプル
> 会員登録ページのフォームを拡張して、会社名を入力必須項目に変更するサンプルです。
> ./app/Customize/Form/Extension/CompanyNameRequiredExtension.php

**Comment by chihiro-adachi** [comment]
#211 で対応しました。
