### ISSUE TITLE
デフォルトブランチを4系のものにしたい

### ISSUE THREAD

**Issue by okazy** [EC-CUBE/ec-cube.github.io#238]
デフォルトが3系のブランチなので4系のドキュメントがどこにあるかわかりにくい。
4系をデフォルトとするか、リポジトリを分けたい。

**Comment by chihiro-adachi** [comment]
@okazy 
4.0ブランチをデフォルトにするで問題ないかと思います。
直接cloneしたりなど影響なければすぐ変更しますがいかがでしょう

**Comment by chihiro-adachi** [comment]
デフォルトブランチを4.0に変更しました。
