### ISSUE TITLE
バージョンアップ時のプロキシ削除コマンドの修正

### ISSUE THREAD

**Issue by rucola-jp** [EC-CUBE/ec-cube.github.io#258]
http://doc4.ec-cube.net/quickstart_update#7-プロキシの再生成

こちらのプロキシファイル削除コマンドは下記が正しくはありませんか？
rm -f app/proxy/entity/src/Eccube/Entity/*.php

**Comment by chihiro-adachi** [comment]
プロキシファイルの出力パスが`app/proxy/entity/src/Eccube/Entity/*.php`に変更されたのは以下のPRを取り込んだ4.0.3からになります。
https://github.com/EC-CUBE/ec-cube/pull/4117

4.0.2までは、app/proxy/entity/直下にプロキシファイルが生成されているので、`rm -f app/proxy/entity/*.php`で正しいかと思っています。

という想定なのですが、何かエラーや問題など発生しましたでしょうか？

**Comment by chihiro-adachi** [comment]
@rucola-jp

**Comment by rucola-jp** [comment]
お返事遅くなってすいません。
もともとのバージョンが8月中に
composer create-project ec-cube/ec-cube ec-cube "4.0.x-dev" --keep-vcs
でインストールしたものであったため、4.0.2とは言えないバージョンだったのかもしれません。
今回のインストールした環境では既にプロキシファイルの出力パスが変更済みのものだった、ということだったように思います。
お騒がせいたしました

**Comment by rucola-jp** [comment]
お返事遅くなってすいません。
もともとのバージョンが8月中に
composer create-project ec-cube/ec-cube ec-cube "4.0.x-dev" --keep-vcs
でインストールしたものであったため、4.0.2とは言えないバージョンだったのかもしれません。
今回のインストールした環境では既にプロキシファイルの出力パスが変更済みのものだった、ということだったように思います。
お騒がせいたしました
