### ISSUE TITLE
デザインのカスタマイズ方法

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube.github.io#48]
- デザインのカスタマイズ方法
  - ブロックの利用
  - 「テンプレートの探索順序」仕様
    - app/templateへtwigファイルを配置する
  - default_flame.twig
  - フォームレイアウトの変更について
    - form.layout.twig
  - gulpを利用したディレクトリ構造

**Comment by Yangsin** [comment]
gulpを利用したディレクトリ構造 はないがクローズします
