### ISSUE TITLE
プラグインでのマイグレーション方法について

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/ec-cube.github.io#71]
プラグインのマイグレーションの作成方法について記載する
- createSchemaを使ったテーブルの生成
- データ投入の方法について
  - ormを利用する場合
  - dbalを利用する場合
    - queryBuilderでのinsert/update

参考：https://github.com/EC-CUBE/ec-cube/issues/1328

**Comment by chihiro-adachi** [comment]
#57

**Comment by Yangsin** [comment]
http://ec-cube.github.io/plugin_bp_migration
