### ISSUE TITLE
プラグイン開発ルールについて

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/ec-cube.github.io#78]
_ec-cubeのIssueから移動_ https://github.com/EC-CUBE/ec-cube/issues/1436

> ttsuru commented on 29 Jan
> プラグインの開発ルールのようなものを定められませんでしょうか。
> 
> 例えば、app/Plugin 以下にはシステムから生成されるファイルを置かないなど、ルールづけできると嬉しいです。

**Comment by Yangsin** [comment]
http://ec-cube.github.io/plugin_bp_about
